APPLY_FIXES: all

DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYRIGHT
  - PYTHON_PYLINT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_TRIVY
  - JSON_JSONLINT
  - MAKEFILE_CHECKMAKE
  - SPELL_LYCHEE
  - REPOSITORY_GRYPE

FILTER_REGEX_EXCLUDE: '(^\.github/workflows/)'
