"""State-space and IMM replay benchmarks for hippocampal open-field data."""
# ruff: noqa: E402

from . import accuracy_model_probability_status_patch as _accuracy_model_probability_status_patch
from . import accuracy_replay_gain_gamma_patch as _accuracy_replay_gain_gamma_patch
from . import advanced_result_empty_threshold_patch as _advanced_result_empty_threshold_patch
from . import advanced_result_missing_group_patch as _advanced_result_missing_group_patch
from . import advanced_result_quantile_array_patch as _advanced_result_quantile_array_patch
from . import advanced_result_status_patch as _advanced_result_status_patch
from . import advanced_result_threshold_validation as _advanced_result_threshold_validation
from . import advanced_result_wrong_map_bootstrap_patch as _advanced_result_wrong_map_bootstrap_patch
from . import axona_data_end_footer as _axona_data_end_footer
from . import benchmark_cell_split_metadata as _benchmark_cell_split_metadata
from . import benchmark_event_limit_validation as _benchmark_event_limit_validation
from . import benchmark_mark_cell_id_validation as _benchmark_mark_cell_id_validation
from . import benchmark_metadata_scope_patch as _benchmark_metadata_scope_patch
from . import benchmark_relative_grouping as _benchmark_relative_grouping
from . import bidirectional_infinite_evidence_patch as _bidirectional_infinite_evidence_patch
from . import bma_options_patch as _bma_options_patch
from . import candidate_active_support_validation as _candidate_active_support_validation
from . import candidate_log_mass_validation as _candidate_log_mass_validation
from . import candidate_support_normalization_validation as _candidate_support_normalization_validation
from . import candidate_support_quality_patch as _candidate_support_quality_patch
from . import cell_split_hashable_grouping as _cell_split_hashable_grouping
from . import cli_float_values_validation as _cli_float_values_validation
from . import clusterless_config_validation as _clusterless_config_validation
from . import clusterless_ground_truth as _clusterless_ground_truth
from . import clusterless_mark_group_validation as _clusterless_mark_group_validation
from . import clusterless_missing_decode_group as _clusterless_missing_decode_group
from . import data_cell_id_validation as _data_cell_id_validation
from . import displacement_config_bool_validation as _displacement_config_bool_validation
from . import displacement_imm_decay_validation as _displacement_imm_decay_validation
from . import duration_candidate_metadata_patch as _duration_candidate_metadata_patch
from . import duration_occupancy_metadata_guard as _duration_occupancy_metadata_guard
from . import duration_occupancy_mode_transition_validation as _duration_occupancy_mode_transition_validation
from . import emission_cell_id_validation as _emission_cell_id_validation
from . import encoding_grid_extra_columns as _encoding_grid_extra_columns
from . import encoding_select_cells_validation as _encoding_select_cells_validation
from . import evidence_status_coercion as _evidence_status_coercion
from . import first_order_imm_diagnostics_validation as _first_order_imm_diagnostics_validation
from . import goal_state_space_integration as _goal_state_space_integration
from . import ground_truth as _ground_truth
from . import ground_truth_cell_id_metadata as _ground_truth_cell_id_metadata
from . import ground_truth_cell_split_strategy as _ground_truth_cell_split_strategy
from . import ground_truth_float_metadata as _ground_truth_float_metadata
from . import ground_truth_integer_metadata as _ground_truth_integer_metadata
from . import ground_truth_sensitivity_metrics as _ground_truth_sensitivity_metrics
from . import ground_truth_window_scope as _ground_truth_window_scope
from . import improved_model_evidence_registry_patch as _improved_model_evidence_registry_patch
from . import kd_encoding_config_validation as _kd_encoding_config_validation
from . import kd_impossible_emission_patch as _kd_impossible_emission_patch
from . import kd_single_bin_momentum_patch2 as _kd_single_bin_momentum_patch2
from . import latent_path_validation as _latent_path_validation
from . import mark_complex_validation as _mark_complex_validation
from . import model_averaged_endpoint_scoping as _model_averaged_endpoint_scoping
from . import model_parameter_validation as _model_parameter_validation
from . import model_numeric_string_validation as _model_numeric_string_validation
from . import observation_sweep_config_validation as _observation_sweep_config_validation
from . import occupancy_candidate_support as _occupancy_candidate_support
from . import olafsdottir_header_float_patch as _olafsdottir_header_float_patch
from . import olafsdottir_zip_safety as _olafsdottir_zip_safety
from . import poisson_input_boolean_validation as _poisson_input_boolean_validation
from . import position_decoding_config_validation as _position_decoding_config_validation
from . import posterior_calibration_summary_patch as _posterior_calibration_summary_patch
from . import pyrecest_bin_center_validation as _pyrecest_bin_center_validation
from . import pyrecest_goal_diagnostics_validation as _pyrecest_goal_diagnostics_validation
from . import pyrecest_numeric_metadata_guard as _pyrecest_numeric_metadata_guard
from . import pyrecest_score_metadata as _pyrecest_score_metadata
from . import recovery_diagnostics_bool_patch as _recovery_diagnostics_bool_patch
from . import result_improvement_seed_validation as _result_improvement_seed_validation
from . import result_quality_audit_scope_patch as _result_quality_audit_scope_patch
from . import reverse_time_terminal_guard as _reverse_time_terminal_guard
from . import score_metadata as _score_metadata
from . import score_metadata_bool_validation as _score_metadata_bool_validation
from . import shuffle_spike_time_order as _shuffle_spike_time_order
from . import simulation_best_row_flags as _simulation_best_row_flags
from . import simulation_recovery as _simulation_recovery
from . import simulation_recovery_count_validation as _simulation_recovery_count_validation
from . import simulation_recovery_event_count as _simulation_recovery_event_count
from . import simulation_recovery_runtime_limits as _simulation_recovery_runtime_limits
from . import sparse_momentum_duration_validation as _sparse_momentum_duration_validation
from . import sparse_momentum_single_bin_diagnostics as _sparse_momentum_single_bin_diagnostics
from . import spike_cell_id_emission_validation as _spike_cell_id_emission_validation
from . import spike_rate_metadata as _spike_rate_metadata
from . import state_space_bin_center_validation as _state_space_bin_center_validation
from . import state_space_bin_count_validation as _state_space_bin_count_validation
from . import sweep_seed_validation as _sweep_seed_validation
from . import time_order_patch as _time_order_patch
from . import well_label_shuffle_patch as _well_label_shuffle_patch
from . import wrapper_return_trajectory as _wrapper_return_trajectory

# Keep score-table metadata and post-hoc decoding consistent before public
# symbols are imported from the patched modules.
_state_space_bin_count_validation.apply_state_space_bin_count_validation_patch()
_score_metadata.apply_model_hyperparam_patch()
_score_metadata_bool_validation.apply_score_metadata_bool_validation_patch()
_model_parameter_validation.apply_model_parameter_validation_patch()
_poisson_input_boolean_validation.apply_poisson_input_boolean_validation_patch()
_model_numeric_string_validation.apply_model_numeric_string_validation_patch()
_displacement_config_bool_validation.apply_displacement_config_bool_validation_patch()
_displacement_imm_decay_validation.apply_displacement_imm_decay_validation_patch()
_candidate_active_support_validation.apply_candidate_active_support_validation_patch()
_candidate_support_quality_patch.apply_candidate_support_quality_patch()
_benchmark_cell_split_metadata.apply_benchmark_cell_split_metadata_patch()
_benchmark_event_limit_validation.apply_benchmark_event_limit_validation_patch()
_benchmark_metadata_scope_patch.apply_benchmark_metadata_scope_patch()
_cell_split_hashable_grouping.apply_cell_split_hashable_grouping_patch()
_benchmark_relative_grouping.apply_benchmark_relative_grouping_patch()
_benchmark_mark_cell_id_validation.apply_benchmark_mark_cell_id_validation_patch()
_clusterless_ground_truth.apply_clusterless_ground_truth_patch()
_clusterless_missing_decode_group.apply_clusterless_missing_decode_group_patch()
_bma_options_patch.apply_bma_options_patch()
_pyrecest_numeric_metadata_guard.apply_pyrecest_numeric_metadata_guard_patch()
_pyrecest_score_metadata.apply_pyrecest_score_metadata_patch()
_pyrecest_bin_center_validation.apply_pyrecest_bin_center_validation_patch()
_pyrecest_goal_diagnostics_validation.apply_pyrecest_goal_diagnostics_validation_patch()
_goal_state_space_integration.apply_goal_state_space_patch()
_spike_rate_metadata.apply_spike_rate_metadata_patch()
_time_order_patch.apply_reverse_emission_time_patch()
_clusterless_config_validation.apply_clusterless_encoding_config_validation_patch()
_data_cell_id_validation.apply_data_cell_id_validation_patch()
_spike_cell_id_emission_validation.apply_spike_cell_id_emission_validation_patch()
