"""Paired synthetic field geometry and explicit decoder resolution controls.

RatInABox supplies the Gaussian place-cell responses. Paths are prescribed in a
common physical domain, not generated by the decoder or by arena-specific walls.
"""

from __future__ import annotations

import itertools

import numpy as np

from .replay_coverage import continuity_metrics, decode_independent
from .replay_coverage_counterfactual import shuffle_base_path
from .replay_coverage_recovery import simulate_path

CORE = np.array([[-70., -70.], [70., 70.]])
TRUTHS = [("continuous", -.5), ("continuous", 0.), ("continuous", .5),
          ("stationary", 0.), ("discontinuous", 0.), ("shuffled_continuous", 0.)]
FACTORS = ["population_seed", "area_m2", "aspect", "sigma_cm", "n_cells",
           "support_domain", "grid_cm", "window_ms", "stride_ms", "observation",
           "likelihood", "estimator", "bin_filter", "continuity_rule"]
KEY = FACTORS + ["path_id", "truth_kind", "gradient"]


def arena_bounds(area_m2, aspect):
    if not np.isfinite([area_m2, aspect]).all() or min(area_m2, aspect) <= 0:
        raise ValueError("area and aspect must be positive")
    extent = 100 * np.array([np.sqrt(area_m2 * aspect), np.sqrt(area_m2 / aspect)])
    return np.array([-extent / 2, extent / 2])


def centered_grid(bounds, spacing_cm):
    bounds = np.asarray(bounds, float)
    if bounds.shape != (2, 2) or not np.isfinite(bounds).all() or np.any(bounds[1] <= bounds[0]) or not np.isfinite(spacing_cm) or spacing_cm <= 0:
        raise ValueError("invalid grid")
    axes = [np.arange(np.ceil(lo / spacing_cm), np.floor(hi / spacing_cm) + 1) * spacing_cm
            for lo, hi in zip(bounds[0], bounds[1], strict=True)]
    if any(not len(axis) for axis in axes):
        raise ValueError("empty grid")
    return np.array(list(itertools.product(*axes)), dtype=float)


def field_population(area_m2, aspect, sigma_cm, normalized_centers, peak_hz=20., floor_hz=.02):
    from ratinabox.Agent import Agent
    from ratinabox.Environment import Environment
    from ratinabox.Neurons import PlaceCells

    centers = np.asarray(normalized_centers, float)
    if centers.ndim != 2 or centers.shape[1] != 2 or not np.isfinite(centers).all() or np.any(np.abs(centers) > .5):
        raise ValueError("centers must be inside normalized rectangle")
    if not np.isfinite([sigma_cm, peak_hz, floor_hz]).all() or sigma_cm <= 0 or not 0 < floor_hz < peak_hz:
        raise ValueError("invalid field width/rates")
    bounds = arena_bounds(area_m2, aspect)
    extent = bounds[1] - bounds[0]
    physical = centers * extent
    env = Environment({"scale": extent[1] / 100, "aspect": aspect, "dx": .08})
    cells = PlaceCells(Agent(env), {"n": len(centers), "description": "gaussian",
        "widths": sigma_cm / 100, "place_cell_centres": (physical - bounds[0]) / 100,
        "wall_geometry": "euclidean", "min_fr": floor_hz, "max_fr": peak_hz})

    def evaluate(points_cm):
        return cells.get_state(evaluate_at=None, pos=(np.asarray(points_cm) - bounds[0]) / 100).T

    return evaluate, physical, bounds


def window_counts(fine_counts, window_ms, stride_ms):
    counts = np.asarray(fine_counts)
    if counts.ndim != 2 or not np.isfinite(counts).all() or np.any(counts < 0) or np.any(counts != np.floor(counts)):
        raise ValueError("counts must be a nonnegative integer matrix")
    if min(window_ms, stride_ms) < 1 or int(window_ms) != window_ms or int(stride_ms) != stride_ms or window_ms % stride_ms:
        raise ValueError("integer ms windows must be divisible by stride")
    starts = np.arange(0, len(counts) - window_ms + 1, stride_ms, dtype=int)
    if not len(starts):
        raise ValueError("event shorter than window")
    prefix = np.vstack([np.zeros((1, counts.shape[1]), np.int64), np.cumsum(counts, axis=0, dtype=np.int64)])
    return prefix[starts + window_ms] - prefix[starts]


def resolution_truth(path, window_ms, stride_ms):
    points = path["midpoints_cm"]
    if not np.isclose(path["fine_s"], .001) or window_ms % stride_ms or window_ms % 2:
        raise ValueError("truth requires even-ms windows and a 1 ms fine grid")
    starts = np.arange(0, len(points) - window_ms + 1, stride_ms, dtype=int)
    if not len(starts):
        raise ValueError("event too short")
    mean = np.stack([points[k:k + window_ms].mean(axis=0) for k in starts])
    centers = starts + window_ms // 2
    idx = np.arange(0, len(starts), window_ms // stride_ms)
    left, right = centers[idx[:-1]], centers[idx[1:]]
    q = np.array([path["covariate"][a:b].mean() for a, b in zip(left, right, strict=True)])
    speed = np.array([path["speed_cm_s"][a:b].mean() for a, b in zip(left, right, strict=True)])
    return {"window_mean_cm": mean, "center_cm": path["edges_cm"][centers],
            "indices": idx, "q": q, "arclength_speed": speed,
            "chord_speed": np.linalg.norm(np.diff(mean[idx], axis=0), axis=1) / (window_ms / 1000)}


def criterion(stride_ms, rule):
    if rule == "literal_20cm_10frames":
        return {"max_jump_cm": 20., "min_frames": 10, "min_displacement_cm": 40.}
    if rule == "time_scaled_4000cm_s_45ms":
        return {"max_jump_cm": 4 * stride_ms, "min_frames": int(np.ceil(45 / stride_ms)) + 1,
                "min_displacement_cm": 40.}
    raise ValueError("unknown continuity criterion")


def decoder_settings(n_cells, sigma_cm, aspect):
    if n_cells == 128 and sigma_cm == 30 and aspect == 1.4:
        return list(itertools.product([4, 8, 16], [10, 20, 40], [5, 10]))
    return [(8, 20, 5)]


def make_paths(seed, population_seed, n_paths, duration_ms):
    if duration_ms < 100 or duration_ms % 5:
        raise ValueError("duration must be >=100 ms and divisible by 5")
    paths = []
    for path_id in range(n_paths):
        parent = None
        perm = np.random.default_rng([seed, population_seed, path_id, 5]).permutation(duration_ms // 5)
        for kind, gradient in TRUTHS:
            if kind == "shuffled_continuous":
                path = shuffle_base_path(parent, perm)
            else:
                path = simulate_path(duration_ms // 5, CORE, kind, gradient, 1000., [seed, population_seed, path_id, 1])
                if kind == "continuous" and gradient == 0:
                    parent = path
            paths.append({"path_id": path_id, "truth_kind": kind, "gradient": gradient,
                          "path": path, "permutation": perm})
    return paths


def generate_observations(paths, evaluate, seed, population_seed, field_id, n_cells=(64, 128), count_rate_hz=300.):
    """Native nested observations; separate common-total generative experiment.

    Common totals do NOT represent removal/restoration of observed cells. New
    identities are sampled using true position, under a conditional likelihood.
    """
    observations = []
    parent = {}
    for trial in paths:
        path, path_id = trial["path"], trial["path_id"]
        n = len(path["midpoints_cm"])
        if trial["truth_kind"] == "shuffled_continuous":
            obs = {key: array.reshape(-1, 5, array.shape[1])[trial["permutation"]].reshape(array.shape)
                   for key, array in parent.items()}
        else:
            rates = evaluate(path["midpoints_cm"])
            class_index = TRUTHS.index((trial["truth_kind"], trial["gradient"]))
            obs_seed = [seed, population_seed, field_id, path_id, class_index, 7]
            native = np.random.default_rng(obs_seed).poisson(rates * .001)
            totals = np.random.default_rng([seed, population_seed, path_id, class_index, 8]).poisson(count_rate_hz * .001, n)
            uniforms = np.random.default_rng([seed, population_seed, path_id, class_index, 9]).random(totals.sum())
            obs = {}
            for cells in n_cells:
                obs["native_poisson", cells] = native[:, :cells]
                conditional = np.zeros((n, cells), np.int64)
                offset = 0
                for t, total in enumerate(totals):
                    p = rates[t, :cells] / rates[t, :cells].sum()
                    cdf = np.cumsum(p)
                    cdf[-1] = 1.
                    identities = np.searchsorted(cdf, uniforms[offset:offset + total], side="right")
                    conditional[t] = np.bincount(identities, minlength=cells)
                    offset += total
                obs["common_count_schedule", cells] = conditional
            if trial["truth_kind"] == "continuous" and trial["gradient"] == 0:
                parent = obs
        observations.append(obs)
    return observations


def decode_chunked(counts, rates, grid, window_ms, likelihood):
    chunks = []
    for lo in range(0, len(counts), 512):
        chunk = decode_independent(counts[lo:lo + 512], rates, grid, window_ms / 1000, likelihood=likelihood)
        chunk.pop("posterior")
        chunks.append(chunk)
    return {key: np.concatenate([chunk[key] for chunk in chunks]) for key in chunks[0]}


def measurement_metrics(points, counts, truth, window_ms, stride_ms, rule, apply_support, rms, entropy):
    valid = (counts.sum(axis=1) >= 3) & ((counts > 0).sum(axis=1) >= 2) if apply_support else np.ones(len(counts), bool)
    params = criterion(stride_ms, rule)
    chosen = continuity_metrics(points, valid_bins=valid, **params)
    eligible = continuity_metrics(truth["window_mean_cm"], **params)["continuity_pass"]
    adjacent = valid[:-1] & valid[1:]
    jump = np.linalg.norm(np.diff(points, axis=0), axis=1)
    idx = truth["indices"]
    # Every intervening support window must be valid; no bridge over excluded bins.
    pairs = np.array([valid[a:b + 1].all() for a, b in itertools.pairwise(idx)])
    core = (idx >= chosen["continuous_start"]) & (idx < chosen["continuous_end_exclusive"])
    selected = pairs & core[:-1] & core[1:] & chosen["continuity_pass"]
    speeds = np.linalg.norm(np.diff(points[idx], axis=0), axis=1) / (window_ms / 1000)
    errors = np.linalg.norm(points - truth["center_cm"], axis=1)
    out = {**chosen, "truth_geometric_eligible": eligible, "n_decoded_bins": len(counts),
           "valid_bins": int(valid.sum()), "valid_adjacent_steps": int(adjacent.sum()),
           "large_jump_fraction": float(np.mean(jump[adjacent] >= 20)) if adjacent.any() else np.nan,
           "median_position_error_cm": float(np.median(errors[valid])) if valid.any() else np.nan,
           "median_posterior_rms_cm": float(np.median(rms[valid])) if valid.any() else np.nan,
           "median_posterior_entropy_nats": float(np.median(entropy[valid])) if valid.any() else np.nan}
    q_decoded = (points[idx[:-1], 0] + points[idx[1:], 0]) / 140
    for name, keep in [("all", pairs), ("selected", selected)]:
        out[f"{name}_steps"] = int(keep.sum())
        out[f"{name}_median_speed_cm_s"] = float(np.median(speeds[keep])) if keep.any() else np.nan
        for axis, x in [("true_coordinate", truth["q"]), ("decoded_coordinate", q_decoded)]:
            for readout, y in [("decoded", speeds), ("true_arclength", truth["arclength_speed"]), ("true_chord", truth["chord_speed"])]:
                finite = keep & np.isfinite(x) & np.isfinite(y)
                prefix = f"{name}__{axis}__{readout}"
                out[f"{prefix}__steps"] = int(finite.sum())
                for suffix, values in [("x", x), ("y", y), ("xx", x * x), ("xy", x * y)]:
                    out[f"{prefix}__mean_{suffix}"] = float(values[finite].mean()) if finite.any() else np.nan
    return out
